### ISSUE TITLE
What do you think about renaming this to `telescope-rg.nvim`

### ISSUE THREAD

**Issue by tjdevries** [nvim-telescope/telescope-rg.nvim#5]
Basically title ^^

It could be where we focus on our rg related work (and then we can either remove some of the things we have in core that people don't use often: maybe configuration options, some pickers, etc).

I am open to this being a bad idea.

cc @Conni2461 as we have talked about this (not sure if it has been mentioned elsewher)

**Comment by weeman1337** [comment]
OK from my side

**Comment by tjdevries** [comment]
OK, let's do it. After we stablize a bit more on this end, then perhaps we can remove some of the pickers from telescope core (maybe when we're ready to do telescope 1.0)

**Comment by weeman1337** [comment]
I don't have permissions to rename it. @tjdevries @Conni2461

**Comment by Conni2461** [comment]
done :)

**Comment by weeman1337** [comment]
Thanks. I will update the documentation asap. No need to rush since GitHub redirects the repo.

**Comment by jesseleite** [comment]
Technically this is not specific to `rg`. It just allows a user to pass options/args to whatever is configured in the user's `vimgrep_arguments` (see https://github.com/nvim-telescope/telescope.nvim/blob/d686fb27998fc130f7b851fb6c540f3f1fe806e8/lua/telescope/config.lua#L538-L559).

If the user wants to configure [thesilversearcher](https://github.com/ggreer/the_silver_searcher) / `ag`, can they not still use `live_grep_raw`? If so, `telescope-live-grep-raw.nvim` makes more sense to me, especially considering the command itself is `:Telescope live_grep_raw`.

**Comment by jesseleite** [comment]
@tjdevries @weeman1337 @Conni2461, technically this feature is not coupled to `rg`. It just allows a user to pass options/args to whatever is configured in the user's `vimgrep_arguments` ([more on this here](https://github.com/nvim-telescope/telescope.nvim/blob/d686fb27998fc130f7b851fb6c540f3f1fe806e8/lua/telescope/config.lua#L538-L559)). If the user wants to configure `ag` / [thesilversearcher](https://github.com/ggreer/the_silver_searcher), can they not still use `live_grep_raw`?

If so, `telescope-live-grep-raw.nvim` makes more sense (to me anyway), especially considering the command itself is `:Telescope live_grep_raw` 😅

**Comment by Conni2461** [comment]
I personally only wanted to get rid of that raw. I think `live_grep_raw` should have replaced `live_grep` at some point.

**Comment by weeman1337** [comment]
That means we would rename it once again to `live_grep`?

**Comment by jesseleite** [comment]
> That means we would rename it once again to live_grep?

That's what I'm proposing yep. I won't die on this hill though, I just don't think this feature is rg-specific or coupled to rg in any way, and users who may want to set up `ag` instead of `rg` in their `vimgrep_arguments` should still be able to use `live_grep_raw` (whatever it ends up being called) 👍 

> I personally only wanted to get rid of that raw. I think `live_grep_raw` should have replaced `live_grep` at some point.

That's fair. The `_raw` is weird I guess. I'd be down for it replacing the default `live_grep`, but I'm often looking for things in gitignored/vendor files, etc. If replacing it is not an option, I'd still lean to `live_grep_raw` for clarity that it's just a variation of `live_grep` that allows you to pass raw command line opts/args.

Anyway, that's my two cents. Appreciate yall, however this ends up ❤️
